### PR TITLE
Update eclipse-emf.jsonnet

### PR DESCRIPTION
**Pull request by merks**
Add .github repository.

### CODE REVIEW

**Review by netomi — APPROVED** [review]

**Comment by merks** [comment]
That only took minutes!  Wow!!  😀

**Comment by netomi** [comment]
repo has been created.

**Comment by netomi** [comment]
semi-automatic :D

**Comment by fperezel** [comment]
Hello,

If you require additional information about GitHub Secret scanning before reviewing this pull request, please refer to the following GitHub document: [Link to GitHub Document About secret scanning]( https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning).

Feel free to reach out if you have any questions.

Thank you,
FP

**Pull request merged**
